spring.application.name=sigeplan-administracao-de-acesso

server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/sigeplan}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sigeplan}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:sigeplan123}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

app.security.jwt.secret=${JWT_SECRET:sua_chave_secreta_muito_forte_aqui_123456789123456789}
app.security.jwt.expiration=${JWT_EXPIRATION:86400000}

app.security.allowed-origins=http://localhost:5173